name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/environment.prod.ts"]'
        env:
          FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
      - run: npm install
      - run: npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "omyperles"
